import AdminNav from './AdminNav'

// ponytail: static file, no fetch — the e2e report is generated by
// `pytest --html=report.html` and copied to public/e2e-report.html;
// this page just frames it, it never calls a live API.
export default function TestReports() {
  return (
    <div className='min-h-screen bg-stone-950 text-stone-100'>
      <AdminNav />
      <div className='max-w-7xl mx-auto px-6 py-8 space-y-4'>
        <div>
          <h1 className='text-lg font-bold text-stone-100'>Test Reports</h1>
          <p className='text-xs text-stone-500'>
            Latest e2e (Playwright/pytest) run. Static file — refresh after re-running the suite.
          </p>
        </div>
        <div className='bg-white rounded-2xl overflow-hidden border border-stone-800' style={{ height: '80vh' }}>
          <iframe
            src='/e2e-report.html'
            title='E2E test report'
            className='w-full h-full border-0'
          />
        </div>
      </div>
    </div>
  )
}
